export const SET_ARTICLES = 'ARTICLE/SET_ARTICLES'
export const SET_ARTICLE = 'ARTICLE/SET_ARTICLE'
export const SET_ARTICLES_BY_CATEGORY = 'CATEGORY/SET_ARTICLES_BY_CATEGORY'
export const SET_CART = 'CART/SET_CART'